export const renderHtml = (css, body) =>
`<html>
    <head>
        <style type="text/css">
.container { background-color: red; } /* Awful, must be overridden! */
.container .span { margin-left: 20px; background-color: blue; color: white; }
.container .button { background-color: darkblue; color: white; font-weight: bold; }
        </style>
        <style type="text/css">
${css}
        </style>
    </head>
    <body>
${body}
    </body>
</html>
`;

function renderComponent(index, appData) {
    return `<div>
    <span>${appData.items[index].name}</span>
    <input type="checkbox" class="${appData.items[index].classNames}"
        value="${appData.items[index].value}" ${appData.items[index].disabled ? 'checked' : ''}>Disable</input>
</div>`;
}

function renderComponents(appData) {
    const components = [];

    for (let i = 0; i < appData.itemNumber; i++) {
        components.push(renderComponent(i, appData));
    }

    return components.join('\n');
}

export const renderBody = (libraryName, classNames, appData) => {
    appData = appData || { itemNumber: 1, items: [ { name: 'foo', value: 'a', classNames: 'checkboxCN' } ] };

    return `<header>
    <h1>${libraryName}</h1>
</header>
<div class="container">
    <!-- TODO -->
    <section class="${classNames.container}">
        <header>
            <h2>Main app</h2>
        </header>
${renderComponents(appData)}
        <button class="button">Update</button>
    </section>
    <aside class="${classNames.help}">
        <header>
            <h2>Help</h2>
        </header>
        <p>There is a main section.</p>
        <p>And an aside controlled by a library.</p>
    </aside>
    <aside class="${classNames.libraryContainer}">
        <header>
            <h2>3rd Party Library</h2>
        </header>
        <!-- Code generated by the library -->
        <div class="container">
            <span class="counter">101</span>
            <button class="button">Increment</button>
        </div>
    </aside>
</div>
<footer>
    <small>The CSS-in-JS Performance Test</small>
</footer>`;
};
